version: '3'

services:
  nginx-proxy:
    build:
      context: ./docker
    container_name: "nginx-proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/sslcreds/:/etc/nginx/sslcreds/
    entrypoint: "tail -f /dev/null"
